#!/bin/zsh

gsettings set org.gnome.desktop.interface icon-theme Arc
gsettings set org.gnome.desktop.interface gtk-theme Arc-Dark
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s river > /dev/null 2>&1 && dbus-run-session river
